

declare class BookDataOption {
  public id: string
  public name: string
  public firstChapter: number
  public lastChapter: number
  public abbreviation: string
}

export function GetBookData() : BookDataOption[] {
  return [
    { id: '0', name: '--Choose an option--', firstChapter: -1, lastChapter: -1, abbreviation: '' },
    { id: '1', name: 'Genesis', firstChapter: 1, lastChapter: 50, abbreviation: 'Gen' },
    { id: '2', name: 'Exodus', firstChapter: 0, lastChapter: 49, abbreviation: 'Ex' },
    { id: '3', name: 'Leviticus', firstChapter: 1, lastChapter: 48, abbreviation: 'Lev' },
    { id: '4', name: 'Numbers', firstChapter: 0, lastChapter: 47, abbreviation: 'Num' },
    { id: '5', name: 'Deuteronomy', firstChapter: 1, lastChapter: 34, abbreviation: 'Deut' },
    { id: '6', name: 'Joshua', firstChapter: 1, lastChapter: 24, abbreviation: 'Josh' },
    { id: '7', name: 'Judges', firstChapter: 1, lastChapter: 21, abbreviation: 'Judg' },
    { id: '8', name: 'Ruth', firstChapter: 1, lastChapter: 4, abbreviation: 'Ruth' },
    { id: '9', name: '1 Samuel', firstChapter: 1, lastChapter: 31, abbreviation: '1 Sam' },
    { id: '10', name: '2 Samuel', firstChapter: 1, lastChapter: 24, abbreviation: '2 Sam' },
    { id: '11', name: '1 Kings', firstChapter: 1, lastChapter: 22, abbreviation: '1 Kgs' },
    { id: '12', name: '2 Kings', firstChapter: 1, lastChapter: 25, abbreviation: '2 Kgs' },
    { id: '13', name: '1 Chronicles', firstChapter: 1, lastChapter: 29, abbreviation: '1 Chr' },
    { id: '14', name: '2 Chronicles', firstChapter: 1, lastChapter: 36, abbreviation: '2 Chr' },
    { id: '15', name: 'Ezra', firstChapter: 1, lastChapter: 10, abbreviation: 'Ezra' },
    { id: '16', name: 'Nehemiah', firstChapter: 1, lastChapter: 13, abbreviation: 'Neh' },
    { id: '17', name: 'Esther', firstChapter: 1, lastChapter: 10, abbreviation: 'Esth' },
    { id: '18', name: 'Job', firstChapter: 1, lastChapter: 42, abbreviation: 'Job' },
    { id: '19', name: 'Psalm', firstChapter: 1, lastChapter: 150, abbreviation: 'Ps' },
    { id: '20', name: 'Proverbs', firstChapter: 1, lastChapter: 31, abbreviation: 'Prov' },
    { id: '21', name: 'Ecclesiastes', firstChapter: 1, lastChapter: 12, abbreviation: 'Eccl' },
    { id: '22', name: 'Song of Solomon', firstChapter: 1, lastChapter: 8, abbreviation: 'Song' },
    { id: '23', name: 'Isaiah', firstChapter: 1, lastChapter: 66, abbreviation: 'Isa' },
    { id: '24', name: 'Jeremiah', firstChapter: 1, lastChapter: 52, abbreviation: 'Jer' },
    { id: '25', name: 'Lamentations', firstChapter: 1, lastChapter: 5, abbreviation: 'Lam' },
    { id: '26', name: 'Ezekiel', firstChapter: 1, lastChapter: 48, abbreviation: 'Ezek' },
    { id: '27', name: 'Daniel', firstChapter: 1, lastChapter: 12, abbreviation: 'Dan' },
    { id: '28', name: 'Hosea', firstChapter: 1, lastChapter: 14, abbreviation: 'Hos' },
    { id: '29', name: 'Joel', firstChapter: 1, lastChapter: 3, abbreviation: 'Joel' },
    { id: '30', name: 'Amos', firstChapter: 1, lastChapter: 9, abbreviation: 'Amos' },
    { id: '31', name: 'Obadiah', firstChapter: 1, lastChapter: 1, abbreviation: 'Obad' },
    { id: '32', name: 'Jonah', firstChapter: 1, lastChapter: 4, abbreviation: 'Jonah' },
    { id: '33', name: 'Micah', firstChapter: 1, lastChapter: 7, abbreviation: 'Mic' },
    { id: '34', name: 'Nahum', firstChapter: 1, lastChapter: 3, abbreviation: 'Nah' },
    { id: '35', name: 'Habbakuk', firstChapter: 1, lastChapter: 3, abbreviation: 'Hab' },
    { id: '36', name: 'Zephaniah', firstChapter: 1, lastChapter: 3, abbreviation: 'Zeph' },
    { id: '37', name: 'Haggai', firstChapter: 1, lastChapter: 2, abbreviation: 'Hag' },
    { id: '38', name: 'Zechariah', firstChapter: 1, lastChapter: 14, abbreviation: 'Zech' },
    { id: '39', name: 'Malachi', firstChapter: 1, lastChapter: 4, abbreviation: 'Mal' },
    { id: '40', name: 'Matthew', firstChapter: 1, lastChapter: 28, abbreviation: 'Matt' },
    { id: '41', name: 'Mark', firstChapter: 1, lastChapter: 16, abbreviation: 'Mark' },
    { id: '42', name: 'Luke', firstChapter: 1, lastChapter: 24, abbreviation: 'Luke' },
    { id: '43', name: 'John', firstChapter: 1, lastChapter: 21, abbreviation: 'John' },
    { id: '44', name: 'Acts', firstChapter: 1, lastChapter: 28, abbreviation: 'Acts' },
    { id: '45', name: 'Romans', firstChapter: 1, lastChapter: 16, abbreviation: 'Rom' },
    { id: '46', name: '1 Corinthians', firstChapter: 1, lastChapter: 16, abbreviation: '1 Cor' },
    { id: '47', name: '2 Corinthians', firstChapter: 1, lastChapter: 13, abbreviation: '2 Cor' },
    { id: '48', name: 'Galatians', firstChapter: 1, lastChapter: 6, abbreviation: 'Gal' },
    { id: '49', name: 'Ephesians', firstChapter: 1, lastChapter: 6, abbreviation: 'Eph' },
    { id: '50', name: 'Philippians', firstChapter: 1, lastChapter: 4, abbreviation: 'Phil' },
    { id: '51', name: 'Colossians', firstChapter: 1, lastChapter: 4, abbreviation: 'Col' },
    { id: '52', name: '1 Thessalonians', firstChapter: 1, lastChapter: 5, abbreviation: '1 Thess' },
    { id: '53', name: '2 Thessalonians', firstChapter: 1, lastChapter: 3, abbreviation: '2 Thess' },
    { id: '54', name: '1 Timothy', firstChapter: 1, lastChapter: 6, abbreviation: '1 Tim' },
    { id: '55', name: '2 Timothy', firstChapter: 1, lastChapter: 4, abbreviation: '2 Tim' },
    { id: '56', name: 'Titus', firstChapter: 1, lastChapter: 3, abbreviation: 'Titus' },
    { id: '57', name: 'Philemon', firstChapter: 1, lastChapter: 1, abbreviation: 'Phlm' },
    { id: '58', name: 'Hebrews', firstChapter: 1, lastChapter: 13, abbreviation: 'Heb' },
    { id: '59', name: 'James', firstChapter: 1, lastChapter: 5, abbreviation: 'Jas' },
    { id: '60', name: '1 Peter', firstChapter: 1, lastChapter: 5, abbreviation: '1 Pet' },
    { id: '61', name: '2 Peter', firstChapter: 1, lastChapter: 3, abbreviation: '2 Pet' },
    { id: '62', name: '1 John', firstChapter: 1, lastChapter: 5, abbreviation: '1 John' },
    { id: '63', name: '2 John', firstChapter: 1, lastChapter: 1, abbreviation: '2 John' },
    { id: '64', name: '3 John', firstChapter: 1, lastChapter: 1, abbreviation: '3 John' },
    { id: '65', name: 'Jude', firstChapter: 1, lastChapter: 1, abbreviation: 'Jude' },
    { id: '66', name: 'Revelation', firstChapter: 1, lastChapter: 22, abbreviation: 'Rev' }
  ]
}
